[package]
name = "serve"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Kaptein network server (axum HTTP/gRPC-Web + tonic gRPC)"

[dependencies]
kaptein-viewmodel = { path = "../kaptein-viewmodel" }
