[package]
name = "frontend-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Kaptein ratatui terminal frontend"

[dependencies]
kaptein-viewmodel = { path = "../kaptein-viewmodel" }
