[package]
name = "kaptein-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "README.md"
description = "Kaptein ratatui terminal frontend"

[dependencies]
kaptein-viewmodel = { version = "0.30.0", path = "../kaptein-viewmodel" }
kaptein-integration = { version = "0.30.0", path = "../kaptein-integration" }
kube = { workspace = true }
k8s-openapi = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
ratatui = "0.30"
crossterm = "0.29"
